### ISSUE TITLE
Impossible access to Thunkable IDE

### ISSUE THREAD

**Issue by manuelcaeiro** [thunkable/docs-thunkable-com#12]
I do not have a Google account and I do not expect to have one since in order to have it Google demands what I do not own, a personal mobile phone number.
I've been offered a course on Android but I would need to use an online Android IDE to follow it up.
I went into your docs quite a while ago and I read the following:
"We currently offer the ability to login to our web platform and mobile app with your Google account. We are hoping to add additional options in the future!"
Today, I went back there and I read the same. I could not avoid to wonder when more precisely will be "the future"... :)
Thank you.

**Comment by mrching** [comment]
Hi there.  Deep apologies for the delay but this week we (finally) launched the ability to login with your email (in addition to Google account).  If you are still interested in checking out Thunkable, come try it at x.thunkable.com
