### ISSUE TITLE
Contradiction in Tab Navigator page

### ISSUE THREAD

**Issue by 10MINT** [thunkable/docs-thunkable-com#5]
There is a contradiction in https://github.com/thunkable/docs-thunkable-com/blob/master/thunkable-cross-platform/2-create/components/layout/tab-navigator.md#adding-icons-to-tab-bar-ios-only 
It says "iOS only", but also "not yet possible [...] for iOS"

**Comment by mrching** [comment]
`Thanks!  We just fixed this.  We'll actually update this again since we should be rolling this out soon.`
